# Generated by Django 4.0 on 2021-12-12 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_remove_todomodel_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todomodel',
            name='duedate',
            field=models.DateField(verbose_name='期限'),
        ),
        migrations.AlterField(
            model_name='todomodel',
            name='memo',
            field=models.TextField(verbose_name='タスクの概要'),
        ),
        migrations.AlterField(
            model_name='todomodel',
            name='priority',
            field=models.CharField(choices=[('danger', 'high'), ('warning', 'normal'), ('primary', 'low')], max_length=50, verbose_name='優先度'),
        ),
        migrations.AlterField(
            model_name='todomodel',
            name='title',
            field=models.CharField(max_length=100, verbose_name='タスク名'),
        ),
    ]
