# Generated by Django 4.0 on 2021-12-12 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0004_alter_todomodel_duedate_alter_todomodel_memo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todomodel',
            name='duedate',
            field=models.DateTimeField(verbose_name='期限'),
        ),
    ]
