# Generated by Django 4.0 on 2021-12-12 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0005_alter_todomodel_duedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todomodel',
            name='memo',
            field=models.TextField(blank=True, null=True, verbose_name='タスクの概要'),
        ),
    ]
