# Generated by Django 4.0 on 2021-12-12 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0006_alter_todomodel_memo'),
    ]

    operations = [
        migrations.AddField(
            model_name='todomodel',
            name='status',
            field=models.CharField(choices=[('done', 'done'), ('WIP', 'WIP'), ('Not started', 'Not started')], default='Not started', max_length=50, verbose_name='ステータス'),
            preserve_default=False,
        ),
    ]
