# Generated by Django 4.0 on 2021-12-12 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0007_todomodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todomodel',
            name='priority',
            field=models.CharField(choices=[('high', 'high'), ('normal', 'normal'), ('low', 'low')], max_length=50, verbose_name='優先度'),
        ),
    ]
